# Generated by Django 5.2.7 on 2025-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
